### ISSUE TITLE
Prework review

### ISSUE THREAD

**Issue by avo1** [ntkhoi/Tip-Calculator#1]
Hi @ntkhoi , thanks for your submission. 👍 Good job with Tip Calculator.

### Quick Comments:

- Good usage of `UserDefaults`. This is one of the methods to pass the data from multiple viewController. We will learn few more ways to do that. 
- Always a good practice to validate user input. Don't let user enter invalid data. You even give more chance for the user to do it wrong with the normal keyboard. It should be the Number Pad.

<img width="316" alt="screen shot 2017-02-08 at 9 06 54 pm" src="https://cloud.githubusercontent.com/assets/10482065/22740457/6a82a018-ee42-11e6-98b9-189214c83f67.png">

- Good job remember the tip amount across app restarts.

- You can try `NSNumberFormatter` and `CurrencyStyle` to make your app adapt with multiple regions, instead of using `String(format: "$%.2f", tipAmount)` For example, for VND, who cares 2 digits after the decimal point? You checked on that, but actually it's not implemented.

<img width="314" alt="screen shot 2017-02-08 at 9 12 11 pm" src="https://cloud.githubusercontent.com/assets/10482065/22740685/39790132-ee43-11e6-95eb-9a2162d59e48.png">

- You can find a better place for animation. Those view controller transition (will appear, will disappear...) already have the animation by default.

Regards,
Dave - iOS instructor

**Comment by ntkhoi** [comment]
Hi @avo1  

> Always a good practice to validate user input. Don't let user enter invalid data. You even give more chance for the user to do it wrong with the normal keyboard. It should be the Number Pad.

- I changed the keyboard to Number Pad to validate user input 

>You can try NSNumberFormatter and CurrencyStyle to make your app adapt with multiple regions, instead of using String(format: "$%.2f", tipAmount) For example, for VND, who cares 2 digits after the decimal point? You checked on that, but actually it's not implemented.
- I use NSNumberFormatter and CurrencyStyle to make my app adapt with multiple regions

**Comment by avo1** [comment]
Thanks for the fix. 

### Next step

Let's schedule a quick call to confirm that this course is a right fit for you. 
We also would like to know a little more about your experience. 
Please book a slot from [here](https://calendly.com/harley/15m).
